apiVersion: v1
kind: Pod
metadata:
  name: apache-bench
spec:
  containers:
  - name: apache-bench
    image: httpd
    command: ["/bin/sh", "-c", "ab -n 500000 -c 1000 http://backend-service.default.svc.cluster.local/"]