apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: argocd

resources:
  - base/argocd.yaml
  - base/argogrpc.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

resources:
  - ingress-class.yaml
  - ingress.yaml

patches:
  - overlays/argocd-server.yaml